#!/bin/env python3

import oksdbinterfaces
import click
import os
import json
import sys
from oksconfgen.dromap2oks import dro_json_to_oks


@click.command()
@click.option('--nomap', '-n', is_flag=True,
              help='Disable generation of the ReadoutMap object')
@click.option('--source_id_offset', '-s', default=0,
              help='Offset to add to source_ids in the generated output')
@click.argument('jsonfile', type=click.Path(exists=True))
@click.argument('oksfile', default='')
def generate(jsonfile, oksfile, source_id_offset, nomap):
  """Simple script to convert a JSON readout map file to an OKS file."""

  dro_json_to_oks(jsonfile, oksfile, source_id_offset, nomap)

if __name__ == '__main__':
  generate()
