#!/bin/env python3
import click
from oksconfgen.get_session_apps import get_database_apps

@click.command()
@click.argument('oksfile')
def get_apps(oksfile):
    appinfo = get_database_apps(oksfile)  

    for session in appinfo:
        print(f"There are {len(appinfo[session])} apps in session {session}: {appinfo[session]}")

if __name__ == '__main__':
    get_apps()
