#!/bin/env python3
import oksdbinterfaces
import coredal

import click
import os
import glob
from oksconfgen.enable import enable

@click.command()
@click.option('--disable', '-d', default=False, is_flag=True,
              help='disable rather than enable the specified resources')
@click.option('--session_name', '-s', type=str, default='',
              help='Name of session to manipulate if not specified the first '
              'session found in the database will be used')
@click.argument('oksfile')
@click.argument('resource', required=True, nargs=-1)
def oks_enable(oksfile, disable, resource, session_name):
  """Script to enable or disable (-d) Resources from the first Session of the
  specified OKS database file"""
  enable(oksfile, disable, resource, session_name)

if __name__ == '__main__':
  oks_enable()
